import { CTA, FAQ, FrameHero, SectionTitle, SiteFooter } from "../components/inner-pages";

const values=["Customer First","Commitment","Excellence","Responsibility"];
const pillars=[["✦","Simplify Daily Operations"],["⌖","Stay Connected Locations"],["⌘","Make Better Decisions"],["↗","Grow With Confidence"]];

export default function AboutPage(){return <div className="inner-page">
  <FrameHero active="about" eyebrow="About Aonepos" title="Streamline Your" highlight="Business Operations" text="At AONEPOS, we are committed to simplifying and optimizing the way businesses operate. Our all-in-one POS solution empowers retailers." image="/assets/about-hero-devices.jpg"/>
  <section className="partner-strip"><h3>Our Businesses Partners Worldwide</h3><div><b>ZYWELL</b><b>PARTNER</b><b>PAX</b><b>star</b><b>EPSON</b><b>ZYWELL</b></div></section>
  <section className="frame-section" id="details"><div className="inner-container"><SectionTitle label="What Drives Us" title="The Values That Drive Everything We Do" text="At AONEPOS, our values shape our technology and customer relationships. We build solutions that prioritize simplicity, performance, and long-term success."/><div className="about-values"><img src="/assets/about-values-photo.jpg" alt="Contactless payment"/><div>{values.map((x,i)=><article key={x}><i>0{i+1}</i><span><b>{x}</b>{i===0&&<small>We design every feature with business owners in mind, ensuring ease of use, reliability and real-world practicality.</small>}</span></article>)}</div></div></div></section>
  <section className="frame-section frame-band"><div className="inner-container"><SectionTitle label="Built For Business" title="Technology That Works Around Your Business" text="Every business operates differently. AONEPOS brings your essential operations together in one flexible platform, helping your team work faster."/><div className="frame-grid four">{pillars.map(([icon,title])=><article className="frame-card" key={title}><i>{icon}</i><h3>{title}</h3><p>Manage sales, inventory and operations from one connected system.</p></article>)}</div></div></section>
  <section className="frame-section"><div className="inner-container"><SectionTitle label="Our Impact" title="Dedicated To Crafting The Ultimate Experience" text="AONEPOS is built to support businesses at every stage — from startup to multi-location enterprise."/><div className="impact-grid">{[["20+","Powerful POS features"],["92%","Customer satisfaction rate"],["300+","Businesses successfully using AONEPOS"],["98%","System uptime reliability"]].map(([n,t])=><div key={n}><b>{n}</b><span>{t}</span></div>)}</div></div></section>
  <section className="frame-section frame-band"><div className="inner-container"><SectionTitle label="Who It’s For" title="Built For Wholesale Businesses Of Every Kind" text="If you sell in bulk, manage accounts, or distribute to other businesses, AONEPOS was designed for you."/><div className="journey-grid">{[["START","Single Location"],["GROW","Growing Business"],["SCALE","Multi-Location"],["LEAD","Enterprise Operations"]].map(([a,b])=><article key={a}><small>{a}</small><b>{b}</b></article>)}</div></div></section>
  <section className="inner-faq"><div className="inner-container"><SectionTitle label="FAQ’S" title="Get Quick Answers About AONEPOS"/><FAQ items={["Can I get a customized solution?","Is AONEPOS suitable for my type of business?","How secure is AONEPOS?","How can I contact support?"]}/></div></section>
  <CTA/><SiteFooter/>
</div>}
