import { CTA, FrameHero, SectionTitle, SiteFooter } from "../components/inner-pages";

const tools=[["▦","Purchase Order Management"],["⌘","Multi-Tier B2B Pricing"],["⌁","Real-Time Inventory Tracking"],["▣","Automated Invoicing"]];
const markets=["Food & Beverage Distributors","Wholesale Goods & Import Traders","Hardware & Building Supplies","Garment & Textile Wholesalers","Electronics Parts Distributors","Cash-And-Carry & B2B Retail"];

export default function SolutionsPage(){return <div className="inner-page">
  <FrameHero active="solutions" eyebrow="Web POS" title="Manage Inventory, Orders &" highlight="Invoicing" text="Wholesale distributors and B2B sellers need one platform to manage purchase orders, pricing, client accounts and invoices." image="/assets/solutions-hero-hardware.jpg" stats={[["50%","Faster stock receiving"],["Real-Time","Stock visibility"],["10+","Integrated modules"]]}/>
  <section className="frame-section" id="details"><div className="inner-container"><SectionTitle label="Built for B2B Sellers" title="Every Tool A Wholesale Business Needs" text="From purchase orders to multi-tier client pricing, AONEPOS handles the complexity of wholesale so your team can focus on moving product."/><div className="frame-grid two numbered">{tools.map(([i,t],n)=><article className="frame-card" key={t}><i>{i}</i><b>0{n+1}</b><h3>{t}</h3><p>Create, approve and track the complete workflow from one connected platform.</p></article>)}</div></div></section>
  <section className="frame-section frame-band"><div className="inner-container frame-split"><img className="photo-img" src="/assets/solutions-warehouse-photo.jpg" alt="Warehouse system"/><div><span className="inner-label">Wholesale & Distribution</span><h2>One System Warehouse To Doorstep</h2><p className="inner-muted left">We connect purchasing, stock, sales and delivery workflows so nothing falls through the cracks.</p><ul className="check-list"><li>Fast barcode scanning for receiving & dispatch</li><li>Automated delivery scheduling</li><li>Mobile POS for field sales & orders</li></ul></div></div></section>
  <section className="frame-section"><div className="inner-container"><SectionTitle label="How It Works" title="From Purchase Order To Final Delivery" text="Keep every wholesale transaction connected from the moment an order is placed to the moment products reach your customer."/><div className="process-row">{["Purchase Order","Inventory","AONEPOS","Order & Invoice","Delivery"].map((x,i)=><article key={x} className={i===2?"brand":""}><i>{["⌘","▥","A","▤","⌁"][i]}</i><b>{x}</b></article>)}</div></div></section>
  <section className="frame-section frame-band"><div className="inner-container"><SectionTitle label="Why Aonepos" title="How AONEPOS Compares To A Basic POS"/><div className="compare-table"><div><b>Feature</b><b>Basic POS</b><b>AONEPOS Wholesale</b></div>{[["Purchase Order Management","—","✓ Full PO Lifecycle"],["Multi-Tier B2B Pricing","—","✓ Unlimited Price Groups"],["Automated Invoicing","Limited","✓ Branded & Emailed"],["Multi-Warehouse Stock","—","✓ Real-Time Sync"]].map(r=><div key={r[0]}>{r.map(c=><span key={c}>{c}</span>)}</div>)}</div></div></section>
  <section className="frame-section"><div className="inner-container"><SectionTitle label="Who It’s For" title="Built For Wholesale Businesses Of Every Kind"/><div className="frame-grid three">{markets.map((x,i)=><article className="frame-card center-card" key={x}><i>{["♨","▤","⌘","♜","▣","▦"][i]}</i><h3>{x}</h3><p>Purpose-built workflows for growing distributors.</p></article>)}</div></div></section>
  <section className="frame-section frame-band"><div className="inner-container frame-split"><div><span className="inner-label">Complete Visibility</span><h2>Know What’s Happening Across Your Business.</h2><p className="inner-muted left">Get a clear view of inventory, pricing and operations across your wholesale business from one dashboard.</p></div><img className="dashboard-img" src="/assets/figma-invoice-dashboard.png" alt="Business dashboard"/></div></section>
  <CTA/><SiteFooter/>
</div>}
