import { CTA, FrameHero, SectionTitle, SiteFooter } from "../components/inner-pages";

const browserFeatures=[["▣","Any Device"],["◫","No Installation"],["☁","Cloud Based"],["⟳","Always Updated"]];
const industries=["Convenience","Grocery","Liquor","Smoke Shop"];
const core=[["01 — Smart Checkout","Smart Checkout Experience"],["02 — Real-Time Inventory","Real-Time Inventory"],["03 — Multi-location","Multi-Location Management"]];

export default function ProductsPage(){return <div className="inner-page">
  <FrameHero active="products" eyebrow="Web POS" title="Bigger Screen. Faster Billing." highlight="Smart Retail." text="From your browser to full business control — in just seconds. No app to install, no hardware to set up." image="/assets/products-hero-terminal.jpg" stats={[["Any Device","Browser based access"],["Real-Time","Cloud sync"],["24 / 7","Always online"]]}/>
  <section className="frame-section" id="details"><div className="inner-container"><SectionTitle label="Your Business. Your Way." title="Full POS Power Right From Your Browser" text="Aonepos Web POS delivers every feature of the Tablet POS directly in your browser."/><div className="frame-grid four">{browserFeatures.map(([i,t])=><article className="frame-card" key={t}><i>{i}</i><h3>{t}</h3><p>Fast, secure and simple for every team.</p></article>)}</div></div></section>
  <section className="frame-section frame-band"><div className="inner-container frame-split"><img className="dashboard-img" src="/assets/figma-invoice-dashboard.png" alt="AONEPOS dashboard"/><div><span className="inner-label">Why AONEPOS</span><h2>Run Your Store Without Being There</h2><p className="inner-muted left">You don’t need to be at the counter to keep your business running. AONEPOS gives you live updates and control.</p><ul className="check-list"><li>Live Sales Dashboard</li><li>Remote Price Updates</li><li>Staff Management</li></ul></div></div></section>
  <section className="frame-section"><div className="inner-container"><SectionTitle label="Built For Retail" title="Every Process. Every Business." text="Whether you sell candy, clothes, or fuel, we’ve got you covered."/><div className="industry-split"><div>{industries.map((x,i)=><article key={x}><i>{["▦","▤","♨","◉"][i]}</i><b>{x}</b></article>)}</div><img src="/assets/products-retail-photo.jpg" alt="Retail checkout"/></div></div></section>
  <section className="frame-section frame-band"><div className="inner-container"><SectionTitle label="Features" title="Everything You Need. Nothing You Don’t." text="The Aonepos Web POS gives your team the same power as a dedicated terminal, delivered through your browser."/><div className="feature-zigzag">{core.map(([k,t],i)=><article key={t}><div><small>{k}</small><h3>{t}</h3><p>Fast, simple tools from any browser. Give your team an easy-to-use interface designed for busy retail environments.</p></div><figure><img src="/assets/figma-invoice-dashboard.png" alt=""/></figure></article>)}</div></div></section>
  <section className="frame-section"><div className="inner-container"><SectionTitle label="Core Features" title="Everything You Need Nothing You Don’t"/><div className="frame-grid three">{["Access Anywhere, Anytime","Advanced Reporting & Analytics","Easy Integrations","Centralised Business Control","Secure Cloud-Based System","Role-Based Staff Access"].map((x,i)=><article className="frame-card" key={x}><i>{["⌂","▥","⌘","▣","♢","◎"][i]}</i><h3>{x}</h3><p>Everything your business needs, connected in one place.</p></article>)}</div></div></section>
  <CTA label="Get Started With Aonepos" title="Ready To Upgrade Your Counter?"/><SiteFooter/>
</div>}
